### ISSUE TITLE
Implement ical export

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#106]

**Comment by leto** [comment]
This looks relevant: https://pypi.python.org/pypi/icalendar/

**Comment by leto** [comment]
@mariobehling are you still interested in this? Perhaps we can carve this into a few GCI tasks?

**Comment by creativepsyco** [comment]
i like this :+1:

**Comment by leto** [comment]
@creativepsyco what exactly are we asking for? Would each event have an ical export URL, or track or what?

**Comment by creativepsyco** [comment]
I think to start with we can have a URL to export the event like
event/123/export/iCal and it will work. The android client can then use the
same URL for bookmarking in calendar instead of creating the event
manually. Similarly we can export track calendars etc. For example
track/123/export/iCal would give the ics file containing all those events.
This way we can embed it somewhere as well. I think Google provides a way
to do it.

**Comment by aviaryan** [comment]
Fields like `start time` and `end time` used in current implementation of ical export are non-standard. We should use `dtstart` and 'dtend' in their place. Other fields should also be renamed according to the ical standard. #204

**Comment by aviaryan** [comment]
@creativepsyco @mariobehling 
What are your opinions about including sessions in tracks. Currently exported `track` is useless because it has nothing except the name. We can add sessions as events or just the track start and end time. (assuming it goes on without break).
Sample track ICS export - http://open-event.herokuapp.com/api/v1/track/5/export/iCal
```
BEGIN:VCALENDAR
BEGIN:VEVENT
DESCRIPTION:
IMAGE URL:
NAME:OpenTech
END:VEVENT
END:VCALENDAR
```

**Comment by aviaryan** [comment]
@juslee The current ical export and event is like
```
BEGIN:VCALENDAR
BEGIN:VEVENT
SUMMARY:dksaffs
DTSTART;VALUE=DATE-TIME:20160406T000000
DTEND;VALUE=DATE-TIME:20160409T000000
COLOR:black
DESCRIPTION:
EMAIL:lokal@fam.com
GEO:-34.3017603194;150.325396484
LOCATION:asdf
LOGO:
URL:
END:VEVENT
END:VCALENDAR
```

It only has the event, no sessions inside it. It will be great to have sessions in the event too, in that way it will become a complete calendar (like the one [for OTS](https://calendar.google.com/calendar/render?cid=t3sacg6lr2s85f51ujggg0usk4@group.calendar.google.com) https://github.com/OpenTechSummit/2016.opentechsummit.net/issues/21). 
What are your views on it ?
