### ISSUE TITLE
Display sponsors in the Sponsors table

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#1131]
![sponsors](https://cloud.githubusercontent.com/assets/15054664/16265008/8df83908-389a-11e6-97d1-9c5e96a88e22.png)

* [ ] Display the sponsors in the table
* [ ] Allow edit, delete and view sponsor details
* [ ] Allow organizer to add sponsor

**Comment by mariobehling** [comment]
To add a sponsor, please direct users to the wizard step 2.

**Comment by mariobehling** [comment]
Actually that feature would make the UI and system even more complex. We already have all the features to edit and change sponsors in wizard step 2. In order to get there, we should simply have a widget in the event dashboard and take out the sponsors tab. Please do not implement a whole tab with the sponsorship features. It is not needed. Please implement instead a widget: https://github.com/fossasia/open-event-orga-server/issues/1136
