### ISSUE TITLE
Generate an html page from the sitemap.xml as a tab in admin/reports

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1318]
Sitemap.xml was implemented here #1288

Please implement a html version for admins in a tab on `admin/reports` to make it easier to keep an overview of the development of the site.

**Comment by aviaryan** [comment]
@mariobehling
Can you point towards a sample sitemap on how ours should look like . 
I researched and like this ( https://www.xml-sitemaps.com/sitemap.html ), a simple list of urls (with page title) and pagination.
Since this feature is meant to be for admins, I guess we don't need to make a menu-based sitemap like [Eventbrite](https://www.eventbrite.com/sitemap/). 

I am thinking of a simple page with Event names and urls to their respective pages (sessions page, schedule page, main page etc). It will have pagination to keep it from getting huge.

**Comment by mariobehling** [comment]
https://www.xml-sitemaps.com/sitemap.html is not so human friendly and does not provide us with value I think.

Actually, you are right, there are two sitemaps
a) a sitemap like eventbrite for users at `/sitemap` (just follow this example)
b) a sitemap with all pages including admin pages at `/admin/sitemap` (you could have a simple in the first version list like in the [below example](http://cdn3.wpbeginner.com/wp-content/uploads/2015/08/html-sitemap-pagesonly.jpg)). I think we should exclude user pages (events, sessions etc) here as it would make the sitemap huge.

![html-sitemap-pagesonly](https://cloud.githubusercontent.com/assets/1583873/16570013/f5e6426a-423d-11e6-9fb7-2156fcc86e7d.jpg)

**Comment by mariobehling** [comment]
@aviaryan Do you still have this issue from June 29 on your to do list?

**Comment by aviaryan** [comment]
@mariobehling If it is needed, I can start working on it.  Should I start working on this ?

**Comment by mariobehling** [comment]
@aviaryan Currently we are linking to an xml on the bottom of the page. So, yes we need something better.

![screenshot from 2016-08-20 10 03 12](https://cloud.githubusercontent.com/assets/1583873/17829899/66a32db2-66bd-11e6-9278-089bbfe26681.png)

**Comment by aviaryan** [comment]
> @aviaryan Currently we are linking to an xml on the bottom of the page. So, yes we need something better.

Since the sitemap will be linked from footer, I guess what I need to make here is the "USER (public) sitemap" . I think the eventbrite's public sitemap is a nice example to follow. 

![eventbrite_sitemap](https://cloud.githubusercontent.com/assets/4047597/17996730/46f0ae70-6b88-11e6-9269-b85183860ce0.png)

@mariobehling What do you think ?

**Comment by mariobehling** [comment]
Looks very nice. Thank you.
