### ISSUE TITLE
Import error if a logo/image file is present

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#1346]
![import](https://cloud.githubusercontent.com/assets/15054664/16487203/e522296c-3ee6-11e6-956c-8d0e889002b6.png)

**Comment by aviaryan** [comment]
Currently `logo` of sponsors is declared as a URL field and url fields should start with `http://` . 
But since when running locally, the storage option is set to "Local", so logo is stored locally and gets a realtive link. Eg `/serve_static/media/events/1/sponsors/1/logo.png` . As this is not a valid url, the API fails on import.

To fix this, we can make the API return images, videos, slides and audio with absolute links. The files will still be stored with relative links in the database (like they are now) but when the data is fetched, the links will get converted to absolute. Since export feature uses API, it will be fixed too. 
I will do it.

**Comment by aditya1702** [comment]
@aviaryan Ok! :+1:

**Comment by aviaryan** [comment]
@aditya1702 I have merged #1351 . Can you check if the issue is fixed on your side. ( you will need to do a export again and then import i.e. don't use old zip )

**Comment by aditya1702** [comment]
@aviaryan Ok will check

**Comment by aditya1702** [comment]
@aviaryan its working fine
