### ISSUE TITLE
some events are not showing up on the API, though they exist on the website

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#1510]
Case in point 

This event exists - 
http://open-event-dev.herokuapp.com/e/34/

But the corresponding API doesn't
http://open-event-dev.herokuapp.com/api/v2/events/34

**Comment by shivamMg** [comment]
@championswimmer Because the event has been removed. On the same note, when a user deletes an event it isn't exactly deleted. It is instead put in the trash and then automatically removed after a period of 30 days. Admins and Super Admins can still see and edit deleted events (`/events/34` and `/e/34`). But I checked right now, even a normal account can see them. I don't know if this has been kept this way or it's a bug.

@aditya1702 @niranjan94 ^

**Comment by niranjan94** [comment]
@shivamMg it's a bug... Will fix
