### ISSUE TITLE
Choose suitable option to store version information

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1702]
For the import/export and API access (e.g. Android app) we need version information. What is the best option to store this version information?

* [ ] Propose and implement the best option for the API
* [ ] Propose and implement the best option for the Event folder zip
* [ ] Change sample zips to the structure https://github.com/fossasia/open-event/tree/master/sample
* [ ] Show version information at event Dashboard

**Comment by the-dagger** [comment]
Furthermore the version information will also help determine the data freshness that is stored on the android app vs the data available on server.
Which will then be used for making network calls to update the data stored.
This is done in the following manner, first the version.json is fetched and then based on it's content **only the** outdated data is downloaded.
So what I'd recommend is to store it separately along with other json files.

**Comment by the-dagger** [comment]
For now, I've send a pull request to store a temporary version.json along with other samples in the open-event repository, so it would be great if anyone from the server team could review it.
[https://github.com/fossasia/open-event/pull/38](https://github.com/fossasia/open-event/pull/38)
Also @mananwason as discussed in the gitter chat, could you explain the structure of sample files?
i.e. why the structure is like `event/1/`

**Comment by shivamMg** [comment]
The best way to solve this would be to use [ETag](https://en.wikipedia.org/wiki/HTTP_ETag) caching. 

For every GET request made by the client, the server sends an ETag (a hash) with the response. This hash is unique to the value of the response being sent. The client saves the response (caches it until next request) and the hash. 

Next time if the client wants to make a request to the same endpoint on the server, he passes an `If-None-Match` header with the request. This header contains the value of the ETag held by the client. The server generates the hash for the resource (or list of resources) at that endpoint. It extracts the hash from the ETag and checks if its value is equal to the generated hash. 

If the generated hash is not equal to the value in the header, it means the resource (or list) has changed. The server would then return a response with the new values. But if the hash has not changed, the server would return a 304 Not Modified response. This response will only contain headers but not the resource (since it is already the same). 

@mariobehling @the-dagger This model is a lot better than the `version.json` model where another API has to be maintained. Plus you are making two requests to fetch a resource, first at the version API and then at the actual endpoint.

**Comment by mananwason** [comment]
So @shivamMg This is a complicated way to do it  since we need to make atleast 6 requests with ```If-None-Match``` header just to check if there were any changes. In the current implementation, we just get the ```Version``` api which gives us the info of all the json updates. So, in just one request we can check if there are any updates or not and make other requests if updates exist. 

Also as pointed out by @mariobehling , It is likely for the internet at any conference to be really bad and If we fire more requests, it tends to congest the network even more. So, I believe the best approach is the go with a versions api only, though whatever value you use to check the version is fine.

**Comment by shivamMg** [comment]
@mananwason does the client app have separate pages for Session, Speaker, etc.

**Comment by mariobehling** [comment]
@shivamMg's suggestion sounds reasonable. We can proceed as below:

![sry77fc](https://cloud.githubusercontent.com/assets/1583873/16909016/e8ff8ae2-4ccf-11e6-8753-9fcaaf3049f7.png)

**Comment by mananwason** [comment]
@shivamMg The client app does have separate pages for Speaker, Session etc. but the request is made at the start of the app. So how it works right now is that : 
Open the app -> Versions.json is downloaded -> Checks each version with what is stored in local db -> If version is not equal, new request is fired to download the respective things (Speakers or Sessions etc.)

@mariobehling As I pointed out earlier, in the approach pointed out by @shivamMg, we need to make many more requests just to check if there are any changes or not. The earlier implementation works perfectly has a very little overhead compare to the suggested implementation and provides offline support too.

**Comment by mariobehling** [comment]
@mananwason Agree, but why can't we add the version information into the event.json and download the event.json right away?

**Comment by mananwason** [comment]
I think that should be okay too but event.json contains a lot of other data as well. We would have to download all that data repeatedly for getting the version information

**Comment by mariobehling** [comment]
Good, please add the version info into the event json then.

**Comment by mariobehling** [comment]
@mananwason @the-dagger Please follow the structure outlined [earlier](https://github.com/fossasia/open-event-orga-server/issues/1702#issuecomment-233263224).

**Comment by mananwason** [comment]
Great @mariobehling. Will do.  @the-dagger could you add the version info in the ```event.json``` file

**Comment by the-dagger** [comment]
Ok, sure.
I will do that @mananwason @mariobehling
