### ISSUE TITLE
drop .json suffix from sample API files

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#1787]
@/all wanted to discuss something - on the sample endpoint here  
https://github.com/fossasia/open-event/tree/master/sample/OTS16 
can we drop the '.json' suffix on the files ? That way it'll be same as API endpoint
Right now we have 
https://raw.githubusercontent.com/fossasia/open-event/master/sample/OTS16/sessions.json as the sessions endpoint on sample repo
if we use
https://raw.githubusercontent.com/fossasia/open-event/master/sample/OTS16/sessions instead then
https://raw.githubusercontent.com/fossasia/open-event/master/sample/OTS16
baseurl will work same as api/v2/event/{eventid} endpoint

**Comment by championswimmer** [comment]
Just to clarify what exactly I mean -
Like we have :

-     https://open-event-dev.herokuapp.com/api/v2/events/9/event
-     https://open-event-dev.herokuapp.com/api/v2/events/9/sessions
-     https://open-event-dev.herokuapp.com/api/v2/events/9/speakers

    and so on

We can have :

-     https://raw.githubusercontent.com/fossasia/open-event/master/sample/OTS16/event
-     https://raw.githubusercontent.com/fossasia/open-event/master/sample/OTS16/sessions
-     https://raw.githubusercontent.com/fossasia/open-event/master/sample/OTS16/speakers

    and so on.

So only by changing the baseUrl (before the `/sessions`) part, we can use both raw github and API server in same way

**Comment by aviaryan** [comment]
> So only by changing the baseUrl (before the /sessions) part, we can use both raw github and API server in same way

Sorry but I have no idea why this is so neccessary. 
The (import) samples are meant to be ready-to-import into orga-server. If we remove .json from the filename, that won't be possible. Do you suggest that we make filenames without extension default ?

Also removing .json will have lots of problems 
- Basic users (users with low tech proficiency) will think the files are binary and probably not open it after export.
- The won't look good overall. 

I think it is better if adjustment is made in the client apps for this rather than changing the samples.
 
@mariobehling @shivamMg What do you think ?

**Comment by championswimmer** [comment]
> Basic users (users with low tech proficiency) will think the files are binary and probably not open it after export.

User's are not supposed to open and **read** the json files are they ?

**Comment by championswimmer** [comment]
> Sorry but I have no idea why this is so neccessary. 
Necessary because we still cannot use any working API endpoint from the server. So at least we can start using ` https://raw.githubusercontent.com/fossasia/open-event/master/sample/OTS16/` as a temporary API endpoint till you guys have data up and running on the server

**Comment by aviaryan** [comment]
> User's are not supposed to open and read the json files are they ?

I am not completely sure on this one. @mariobehling ?

> Necessary because we still cannot use any working API endpoint from the server. So at least we can start using https://raw.githubusercontent.com/fossasia/open-event/master/sample/OTS16/ as a temporary API endpoint till you guys have data up and running on the server

You say this as "temporary", so why not add some temporary code to check for githubusercontent server and append urls with .json . But yes, this depends on the previous question. If users are not supposed to read the json files, then we can go with removing extension from samples and this can be avoided.

**Comment by shivamMg** [comment]
@championswimmer Do you want a temporary place to fetch data? I can setup a temporary server if you like.

**Comment by championswimmer** [comment]
@shivamMg 
That would be good if you could do so

**Comment by mariobehling** [comment]
>> So only by changing the baseUrl (before the /sessions) part, we can use both raw github and API server in same way

> Sorry but I have no idea why this is so neccessary. 
The (import) samples are meant to be ready-to-import into orga-server. If we remove .json from the filename, that won't be possible. Do you suggest that we make filenames without extension default ?

Honestly, I am not sure, what is the best solution. I just want to make sure, we stick to standards as much as possible. So what is the most common thing to do?

**Comment by mariobehling** [comment]
@shivamMg Not sure, what you mean by temporary server. We have the heroku deployment that can be used for testing.

**Comment by championswimmer** [comment]
@aviaryan @mariobehling @shivamMg 
I have used many services before that emulate a REST api on static sites (like gh-pages) 
As I see it   
1. There are no _standards_ that say that we cannot drop .json suffix 
2. The imported files are for using with the generators. Not be read or written to manually. So I don't see why them not having .json can harm the user. And the ones who want to edit, can still open it in any text editor. 
3. The advantage I see here is both the raw.githubusercontent URL and the orga server API can be used without any changes in the client side. Making a hacky change to add .json suffix on the paths when they start with github is not ideal at all. 

Please drop the .json suffix, if these points seem reasonable. If not please let me know if there are any counter points.

**Comment by mariobehling** [comment]
@championswimmer Sounds reasonable to me.

@aviaryan Please provide input. Also there is the question that the sample JSON files divert from the APIs. Please follow up on this here https://github.com/fossasia/open-event-orga-server/issues/1786

**Comment by aviaryan** [comment]
> The advantage I see here is both the raw.githubusercontent URL and the orga server API can be used without any changes in the client side. Making a hacky change to add .json suffix on the paths when they start with github is not ideal at all.

I don't find this the sufficient reason to drop `.json` from the extension. 
Maybe because the need to use github samples is only till a good sample is available on the server. When a complete sample is available, this won't be needed. (I have updated [FOSSASIA samples](https://github.com/fossasia/open-event/pull/50))
I like @shivamMg 's idea of creating a temporary server. It should not take long and will work as follows - 

Suppose url of temp server will be xxx.heroku.com . 
I see that in webapp you are accepting the root url of the API. 
Like `raw.githubusercontent.com/fossasia/open-event/samples/ots16`
So instead of that you can set `xxx.heroku.com/raw.githubusercontent.com/fossasia/open-event/samples/ots16/` as the root url. 
Then if I am correct the webapp will send request at `xxx.heroku.com/raw.githubusercontent.com/fossasia/open-event/samples/ots16/event` for the event information.
Here is where the heroku server will come into play and it will download 
`raw.githubusercontent.com/fossasia/open-event/samples/ots16/event` + '.json' and return the file data.
 
@championswimmer 
It should not take much time to develop either in Flask or NodeJS. 
If you are not satisfied, let me know and I will start working on dropping the .json from the export files.

**Comment by mariobehling** [comment]
@aviaryan Thought the custom_forms.json will become forms.json?

**Comment by championswimmer** [comment]
I get your points. I agree with everything.

But what exactly, technically, is the disadvantage of dropping the json
suffix.

Even if server starts having full samples, what if the app is sleeping on
heroku?

**Comment by championswimmer** [comment]
All your suggestions involve writing code somewhere or the other (that too
for no real functionality addition),  and we are short on time :(
Renaming is easier I believe

**Comment by aviaryan** [comment]
@championswimmer Ok. WIll work on dropping the json.

**Comment by aviaryan** [comment]
> @aviaryan Thought the custom_forms.json will become forms.json?

ok.
