### ISSUE TITLE
Api end point name for microlocation

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-orga-server#18]
Please Change name to microlocation instead of microlocations.

**Comment by rafalkowalski** [comment]
Could you explain me where?

**Comment by rafalkowalski** [comment]
I assumed that we can have few microlocations, so we want only one?

**Comment by mariobehling** [comment]
@rafalkowalski +1

**Comment by mananwason** [comment]
Rafal I was just talking about the address as all other addresses are like
/event, /sponsor etc. But this is plural.

**Comment by rafalkowalski** [comment]
I changed it, Is it good?
https://github.com/fossasia/open-event-orga-server/commit/9aa35b07f7b1e4417c4ec49c215a93539a5a2370

**Comment by mananwason** [comment]
I just intended to end the discrepency. Plural sounds better. Please change in json response as well as shown here
![image](https://cloud.githubusercontent.com/assets/10570249/7799908/6bad371e-032a-11e5-8f1c-1b433b465850.png)

**Comment by championswimmer** [comment]
The idea of 'microlocations' is for locations inside the area. like halls,
auditoriums, stages etc.
microlocations will be optional, not all events might have detailed event
area plans, but if microlocations are used, they will be plural, because
there will be multiple microlocations.

microlocation != event location
event location is specified in the /event api as a latitude and longitude.

**Comment by rafalkowalski** [comment]
@championswimmer I have changed microlocation to microlocations.
I think we should close this ticket
https://github.com/fossasia/open-event-orga-server/commit/aa527499608b6e33ce01355d4cbcc10d92fb5887
