### ISSUE TITLE
Move contact info from "Profile to "Settings"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1822]
Please implement the following: In User Settings "add email and phone details". Move them from "Profile into "Contact Info" in the settings area.

**Comment by SaptakS** [comment]
@mariobehling I think we can move the entire "Profile" into the settings area. Full Name, Desriptions, Image, etc. can come under "General Info". Otherwise keeping it in 2 different places can be confusing. Moreover, everywhere from facebook to twitter, we have the "Profile" info in settings area. Just a thought. What do you think?

**Comment by mariobehling** [comment]
@SaptakS Yes, I was thinking about that, but I checked out Eventbrite, Meetup and Twitter and they all keep it separate. We are not keeping the data at two different places -> Email and Phone should be moved completely and not kept at the profile anymore.

**Comment by niranjan94** [comment]
@mariobehling will make the change.
