### ISSUE TITLE
Access denied error after accepting a moderator invitation of an event

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#1901]
What resulted in this error.

- From `user1@gmail.com`. Event ID `53` http://open-event-dev.herokuapp.com/events/53/ . 
- Added `user2@gmail.com` as a moderator. 
- Logged into `user2@gmail.com`. Accepted the invite. 
- Got the **Access denied** error when I try to reach  http://open-event-dev.herokuapp.com/events/53/ .

**Comment by mariobehling** [comment]
Thanks. Please also check, what additional fields need to be implemented here: https://open-event-dev.herokuapp.com/admin/permissions/ and how we need to change the standard config.

**Comment by shivamMg** [comment]
@mariobehling We can add a feature to let admin define custom event roles. Organizer, Track Organizer and Moderator would be built-in. If other roles are required, the Admin or Super Admin can create one with a their separate set of permissions. These Roles would be available to the Organizers of Events. What do you think? Shall I create a separate issue, this bug is solved.

**Comment by mariobehling** [comment]
@shivamMg The system is already complex enough and no other system have this kind of feature. The user does not expect to have this feature at that time and we need to focus on making our system work now.

**Comment by shivamMg** [comment]
@mariobehling Ok, closing this issue then.
