### ISSUE TITLE
Ticketing and Payment system for organizers

### ISSUE THREAD

**Issue by aditya1702** [fossasia/open-event-orga-server#1920]
- [x] Allow organizer to add multiple tickets
- [x] Implement fee to be added to the overall ticket cost
- [x] Allow user to pay in the currency of his/her choice
- [x] Implement tax option in payment system
- [x] Allow organizer to create PayPal account

**Comment by aditya1702** [comment]
Will implement 2nd point in #2023

**Comment by niranjan94** [comment]
@aditya1702 while the organizer is choosing a currency in the event creation wizard, please store the **3 letter ISO 4217** currency code (e.g. USD, INR) in the database instead of the name of the currency. All payment gateways require a currency code and this is the right way to store a currency. 

For reference: [The list of ISO 4217 Currency Codes](http://www.xe.com/iso4217.php)

**Comment by niranjan94** [comment]
@aditya1702 ... Thanks :)
