### ISSUE TITLE
Prepare widget in event detail page

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1998]
Add buttos which allow organizer to generate android and web app

- [x] UI in event details page 
- [x] add AndroidApp connection
- [x] add WebApp connection

**Comment by mariobehling** [comment]
Please test this in the live app. I do not see this is working yet.

**Comment by rafalkowalski** [comment]
Currently I've added only UI, I haven't added communication between Android and Web App yet

**Comment by mariobehling** [comment]
Ok, then:
* [ ] Only show an app it is is enabled. If one of the two apps is not enabled - show nothing. Do not show: "AndroidApp URL is not defined. Please inform system Administrator". We do not want users to talk to an administrator.
* [ ] Do not show the widget at all if no apps are enabled
* [ ] Rename Widget to "Apps" instead of microservices
