### ISSUE TITLE
refactor: use minified and compressed assets

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#211]
The css for example is 2.2 MB is size and takes considerable time to load 
![screenshot from 2016-03-19 20 06 56](https://cloud.githubusercontent.com/assets/1327050/13899207/454f2f62-ee0e-11e5-9e59-e20a1d3a2a66.png)

**Comment by leto** [comment]
My first question is: Why is the CSS so large, it must be mostly unused. Can we use a different layout.

In general I am all for minifying+compressing CSS/JS/etc in production, but I don't want it during development locally. It makes debugging a pain, so it should be able to be turned on/off.

**Comment by aviaryan** [comment]
> Why is the CSS so large, it must be mostly unused. Can we use a different layout.

:+1: . I think [materialize](http://materializecss.com/) will be an excellent replacement for the other frameworks used here.

Why ?
* All components (including icons) we are currently using in open-event-server's frontend are supported by the framework.
* Modern material design
* **Excellent mobile support** ([Have a look](http://materializecss.com/mobile.html))

The CSS is around **170kb uncompressed**. And it should be all that we would need. 

[materialize on GitHub](https://github.com/Dogfalo/materialize)

**Comment by niranjan94** [comment]
Actually, that entire stylesheet is unused. So, I have removed it and also minified and compressed the assets. The PR #198 takes care of that. 

**The PR does:**
1. Combines, minifies, caches and servers all the javascript and css assets using [Flask-Assets](http://flask-assets.readthedocs.org/en/latest/)
2. Re-arranges the static assets for easier maintenance. 

**The PR removes:**
1. `material-fullpallette.css` - Because it's unused and takes up a lot of bandwidth
2. `material-design-icons` - Unused. Only Glyphicons are used everywhere.

**Comment by niranjan94** [comment]
@championswimmer Could you have a look at PR #217 .. ? I believe it resolves this issue.
