### ISSUE TITLE
Scaling up the system to handle increase in the number of users/traffic

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#2415]
As pointed out by @mariobehling, 

We will have to start thinking about how we can scale up our current system on the cloud easily, in case there are more number of users/traffic at one point. 

We will need to think about load balancing and scaling up of the app and PostgreSQL database servers.

Any suggestions and inputs are welcome.

**Comment by mariobehling** [comment]
@leto @juslee Any input/ideas from your side on this?

**Comment by ogai** [comment]
First of all congratulations for this interesting project! I have been working on two similar projects and we have discussed a lot [HA](https://en.wikipedia.org/wiki/High_availability), [LB](https://en.wikipedia.org/wiki/Load_balancing_(computing)) and [R](https://en.wikipedia.org/wiki/Replication_(computing)). All related to [scalability](https://en.wikipedia.org/wiki/Scalability).

Without forgetting the well known sentence of Donald Knuth
> premature optimization is the root of all evil

The bottleneck of a web application is normally the database.

Regarding load balancing of the database, I see you are using Heroku and PostgreSQL. The former has [Adept Scale](https://elements.heroku.com/addons/adept-scale). The later has [Streaming Replication](https://www.postgresql.org/docs/9.4/static/warm-standby.html#STREAMING-REPLICATION), with which you can have as many replicated databases as you need, and the users are normally load balanced between them. Heroku already offers this named [following masters](https://devcenter.heroku.com/articles/heroku-postgres-follower-databases).

I will write a blog post soon about all this, feel free to follow me [@ogai](https://twitter.com/ogai).

**Comment by SaptakS** [comment]
@ogai thanks for the info.. Looking forward to your blog.

**Comment by leto** [comment]
My first suggestion is to decide on some concrete numbers that we want to be able to handle.

How many concurrent web requests and DB requests do we want to handle? Then we have a goal to achieve.

My guess is that our traffic will be very read-heavy (1000s of people looking at the latest schedule just before and during the conf) but won't be as write-heavy. We could probably benefit from having a read-only DB replica, which all the read-operations go to. This greatly improves "contention" in times when we have lots of reads and writes happening at the same time.

We will also want layers of caching. If there is an expensive API read operation, we could store the results in Redis for a certain time (maybe a few minutes or longer). If the result is already in Redis, we use that, otherwise we do the slower SQL query.

We can even cache entire HTML pages in Redis for a short time, so that expensive pages (like leaderboard or anything that has to make a bunch of SQL queries to generate stats/etc) will only need to be generated every few minutes instead of for every single user that requests the page.

Some next steps: Which are the slowest parts of our system? Where are the bottlenecks? What starts to degrade/fail under load? That is where we want to focus our attention.

We may also want to use something like Cloudflare (to protect against DDoS's) or at least a CDN to offload as many requests from our servers as possible. Cloudflare/CDNs will also greatly reduce our bandwidth bill and are sometimes worth it just for that.

**Comment by ogai** [comment]
There are some problems with caching:

- The dynamic content of the page when caching the whole page, like name of the user, the number of notifications, or the current language. Some web application frameworks like Django have [template fragment caching](https://docs.djangoproject.com/en/1.10/topics/cache/#template-fragment-caching) for caching only a part of the page (in the current language of the user if you have I18N).
- If a user edit the content, but she sees the cached page without her editions, she will be very confused. E.g. editing an event and showing the event page immediately thereafter - from the old cache or lagged replica, outh!
- Race conditions when invalidating the cache, e.g.[why is cache invalidation considered difficult?](https://www.quora.com/Why-is-cache-invalidation-considered-difficult) and related questions.

**Comment by ogai** [comment]
There are also some problems with serving static content (with a CDN or whatever):

- **minifying** and **compressing** to save on bandwidth (for the server and the client) and to speed up the building of the page on the client. If you serve the content yourself, you also want to increase with it the number of concurrent users you can serve per second with a single server. This is related to the second typical bottleneck, the bandwidth, and to the third, the disk.
- **versioning**: after each new deploy changing some static files like JavaScript or CSS, you need to tell the clients somehow to use the new static files, not the old. This problem exacerbetes if you ask the browser to cache static files.
- **merging**: glue static files together to avoid hitting the maximum simultaneous connections of the browser, which is about 8.

You can check if you (or anyone else) is doing all the above right with [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/). This is a project I worked on which gets 100 out of 100 points for the desktop and mobile version: https://timefyme.com

**Comment by mariobehling** [comment]
Thank you for helping to clear up this question. The Google Cloud team agreed to support the project and we will go with this solution. I will open a dedicated issue. Cheers.
