### ISSUE TITLE
Not saving additional links

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2780]
Adding a blog link to the create event wizard page 1, it does not get saved and displayed on the public page.

**Comment by Marauderer97** [comment]
@mariobehling I tried doing the same and it works..
![image](https://cloud.githubusercontent.com/assets/20185076/21647983/6e18f3d0-d2c2-11e6-92d4-a91566509b65.png)
![image](https://cloud.githubusercontent.com/assets/20185076/21648014/81c90118-d2c2-11e6-8b5b-611135753fb5.png)
One suggestion though, since the link gets added only if we specifically list it as a blog(and not Blogger or Myblog) won't a dropdown be more practical?

**Comment by SaptakS** [comment]
@mariobehling can you confirm this error still exists? I don't find it in the heroku deployment. http://open-event-dev.herokuapp.com/events/302/

**Comment by niranjan94** [comment]
Seems to work fine on eventyay.com & open-event-dev ... Closing this for now.
