### ISSUE TITLE
Email Update option no longer available

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2797]
The options to subscribe/unsubscribe to email updates from events are no longer available.

Please make a list of updates and enable them again.

These were solved here https://github.com/fossasia/open-event-orga-server/issues/1179 and here https://github.com/fossasia/open-event-orga-server/issues/1236

![screenshot from 2016-12-31 16-17-32](https://cloud.githubusercontent.com/assets/1583873/21578114/cce33764-cf74-11e6-8d97-70f978e1fc3f.png)

**Comment by nikhilrayaprolu** [comment]
I'll try working on this @mariobehling @niranjan94 @SaptakS

**Comment by nikhilrayaprolu** [comment]
@mariobehling @niranjan94 @SaptakS I dont find this bug on my pc.
![screenshot from 2017-01-05 21-43-38](https://cloud.githubusercontent.com/assets/15216503/21687620/0ad604b0-d390-11e6-8837-d640f5baf0a4.png)

**Comment by niranjan94** [comment]
@nikhilrayaprolu try these. Let's see if the bug comes up in any of this.
1. Import an event and check
2. Create two users A & B. Create an event from user A. Add user B as a speaker in that event. Now check the email settings in User B.

**Comment by niranjan94** [comment]
@nikhilrayaprolu were you able to reproduce this with what I have said above ?

**Comment by mariobehling** [comment]
Bug is still vaild on eventyay. Please see below. There are no options to switch on or off anything.

![screenshot from 2017-01-12 21-01-00](https://cloud.githubusercontent.com/assets/1583873/21906136/5630d03c-d90a-11e6-8280-8a547f2c9e48.png)

**Comment by shubham-padia** [comment]
If no one else is working on this, i'd like to work on this.

**Comment by shubham-padia** [comment]
@niranjan94 @SaptakS 
Finally :sleepy:, found the cause behind this and why it was displaying for @nikhilrayaprolu .

- `message_settings` table is used for managing the mail settings at `admin/messages/`
- The same `message_settings` table is used to handle user email preferences (which IMO is a mistake as it does not contain a user id field) and you cannot see the settings until that table is initialized with appropriate values.

Steps to recreate the issue properly
- create a new db
- go to /settings/email-preferences/, you will observe the conditions mentioned in the issue description
- go to `/admin/messages` and click on save once, this will populate the table for the first time
- Then you can see the output which @nikhilrayaprolu mentioned

This exposes two main issues:
- Implement a table for maintaining users' email preferences and make relevant changes.
- pre-populate `message_settings`, so that relevant mails work without user going atleast once at `/admin/messages` to initialize the values.

**Comment by shubham-padia** [comment]
^^ Should I create relevant issues and move ahead.

**Comment by SaptakS** [comment]
@shubham-padia, no need to create separate issues. Please do the needful and solve the issue. I think we will need and users' email preference table and prepopulate it, right?

**Comment by mariobehling** [comment]
Unfortunately the issue has not actually been solved. Still valid on eventyay. There are no options for email updates for specific events.

![screenshot from 2017-01-28 17-19-56](https://cloud.githubusercontent.com/assets/1583873/22397965/23a89354-e57e-11e6-8792-5069a28fcd5a.png)

**Comment by shubham-padia** [comment]
@mariobehling This bug was at database creation phase which has been fixed, could you please go to `/admin/messages` and click on save once. That should fix it :)

**Comment by mariobehling** [comment]
Thanks!
