### ISSUE TITLE
Errors in calculation of ticket sales

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2878]
The calculation of ticket sales is erroneous. If discounted or free tickets are sold the sales overview still shows the normal ticket price instead of the real ticket price.

Expected: Show the real sales revenue in the sales column.

The total already shows the correct income.

![screenshot from 2017-01-08 23-51-36](https://cloud.githubusercontent.com/assets/1583873/21754310/07b07976-d5fe-11e6-986c-0548ced58c6f.png)

E.g. if you have admin access compare: https://eventyay.com/events/6/tickets/

**Comment by magdalenesuo** [comment]
I'd like to do this.

**Comment by SaptakS** [comment]
@mariobehling I have a small doubt in this issue. In this issue you say to show the discounted ticket price. But the discount really is on the order rather than a ticket. So basically a ticket can never have a discount. 

An order can have a discount. But at the same time an order can have multiple tickets in it. So showing discounted sales in tickets doesn't really make sense don't you think? Because if there are 2 different types of tickets in the same order, then the discount is on the entire order rather than a single type of ticket. So the discount isn't exactly a ticket property rather an order property.

@niranjan94 @mariobehling @magdalenesuo what do you think?

**Comment by mariobehling** [comment]
@SaptakS The discounts are on the ticket. A user can get e.g. one discounted community ticket and one early bird ticket (at normal price). So the tickets are in fact discounted. We follow the same way as eventbrite and eventnook.

**Comment by SaptakS** [comment]
@mariobehling but right now we can apply the discount code only on the total order rather than each ticket. We can't give discount exactly like specific to a particular ticket. In DB also I think the discount code is stored with order rather than all the tickets bought. @niranjan94 correct me if I am wrong.

**Comment by mariobehling** [comment]
@SaptakS I also compared this with the dashboard of eventnook. Here as well the tickets are calculated at the price they are really sold. If two community tickets were sold at the price of 1 Dollar, it cannot show up as 42 Dollars. So, this does not make sense. It should show the real price.

**Comment by SaptakS** [comment]
@mariobehling Suppose for example there is an order with 1 community ticket of $10 and 1 early bird ticket of $20. Now I apply a promocode which gives me $5 discount. So the final total will be $10 + $20 - $5, right? But we can't say that the real price in which community ticket is sold is $5 instead of $10 or something like that. Because the promocode is applied on the entire order.

> I also compared this with the dashboard of eventnook. Here as well the tickets are calculated at the price they are really sold.

In this case I think we might have to modify the implementation. @niranjan94 your views because you know this functioning better than me. Correct me if I am wrong.

**Comment by mariobehling** [comment]
@SaptakS I do not know how to explain: You cannot show up 42USD in one row and then the final total calculation of 1USD in another row. All numbers need to make sense. If there is a question how we save it in the DB or how the discount is calculated, then we need to fix the DB. It is wrong for the accounting otherwise. You can continue to explain this to me, but the fact is: No customer will understand if it shows up like that.

**Comment by SaptakS** [comment]
> You cannot show up 42USD in one row and then the final total calculation of 1USD in another row. All numbers need to make sense.

That can be solved by showing like this maybe:
![screenshot from 2017-01-10 01-05-03](https://cloud.githubusercontent.com/assets/9530293/21781046/d4bdf256-d6d3-11e6-9257-1aa4d40909f6.png)


But the main question is should it be implemented in order or ticket level. Because if it has to be in ticket level then I think the code needs to be changed.

**Comment by mariobehling** [comment]
> Because if it has to be in ticket level then I think the code needs to be changed.

Yes, the code needs to be changed then. Eventbrite and Eventnook do it that way. If we do it differently everyone will be confused.

**Comment by mariobehling** [comment]
Here is an example of Eventnook. We should follow this simple approach. The income is calculated - based on the real income (not some theoretical income without discounts). The row of the Early Bird tickets show the real income.

![screenshot from 2017-01-09 20-59-08](https://cloud.githubusercontent.com/assets/1583873/21781219/d2f5655a-d6ae-11e6-9205-d8e75f54c886.png)

**Comment by SaptakS** [comment]
@mariobehling got you. I think the way of implementation needs to be changed rather than the way of showing. I will look into it.

**Comment by SaptakS** [comment]
@magdalenesuo you can proceed with this issue and #2879 once #2906 is merged. The logical error has been fixed. You can now show the discounted price for each tickets as said in the issue.
