### ISSUE TITLE
event page return 404 error

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#2911]
https://eventyay.com/explore/bengaluru/events/
Event "Science Hack India" visibles on events list but we can't go to details.
We get 404 error https://eventyay.com/e/7c140a8f/

**Comment by SaptakS** [comment]
@mariobehling @rafalkowalski I think this issue is because there was an issue related to public link on copying events #2837 which was fixed. Due to that fix, these links must have become invalid because the changes get implemented from the next events created. This is the only logical reason or explanation I can come up with. @niranjan94 what do you think?

**Comment by mariobehling** [comment]
Yes, I think so.

I deleted the event. If this issue should re-appear we can reopen it. Thanks!
