### ISSUE TITLE
Page titles shown as {app name} - {page name}

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#2949]
Continuing from https://github.com/fossasia/open-event-orga-server/pull/2941#discussion_r96114730

> With this change, all pages will come like "Open Event - Login", "Open Event - Manage events", "{app name} - {page name}" etc.. Is this right?
I think "{page name} - {app name}" is more natural and practical.
Only on homepage we should have {app name} - {tagline}

---

Correct way to make titles for site pages is {page name} - {app name}.

**Comment by magdalenesuo** [comment]
@aviaryan I tried to change it as @mariobehling asked for. This was followed in Eventbrite site, so I made the changes for the whole site in general rather than the Home page alone. :sweat_smile: 
![screenshot from 2017-01-14 18-39-12](https://cloud.githubusercontent.com/assets/20799954/21955087/39d5cf16-da89-11e6-87d9-3c8247c4241d.png)

**Comment by aviaryan** [comment]
@magdalenesuo 👍 Ok, I can understand why you did that. But I am not sure if that's the way to go.
What do you think? @mariobehling @hpdang
