### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by yasirunilan** [fossasia/open-event-orga-server#3020]
I followed the intallation guide , when I tried to install the requirements  by running 
pip install -r requirements.txt

I get this error 
Error: You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
What could be wrong?

**Comment by aviaryan** [comment]
If you are on Linux, apt install libpq-dev



On 22-Jan-2017 1:36 PM, "yasirunilan" <notifications@github.com> wrote:

I followed the intallation guide , when I tried to install the requirements
by running
pip install -r requirements.txt

I get this error
Error: You need to install postgresql-server-dev-X.Y for building a
server-side extension or libpq-dev for building a client-side application.
What could be wrong?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/open-event-orga-server/issues/3020>, or mute
the thread

**Comment by niranjan94** [comment]
@yasirunilan please do not open an issue for assistance during installation. You'd get better support at our Gitter channel :smile: 

https://gitter.im/fossasia/open-event-orga-server
