### ISSUE TITLE
Session Overview with scrollbars, long text, draft issue

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3059]
The session overview has a few issues:
* [ ] shows scroll bars after saving sessions - Expected: No scrollbars
* [x] After user adds more information to an accepted session, the session shows up again in draft mode - Expected: Session should stay in same mode as before
* [ ] The abstract text in overview is very long - Expected: Only show the first 200 characters of the abstract

![screenshot from 2017-01-29 04-36-14](https://cloud.githubusercontent.com/assets/1583873/22401666/db285d58-e5dc-11e6-9c46-1b5e3bf711c3.png)

**Comment by mariobehling** [comment]
Thanks, definitely a good improvement and the scroll bar does not appear so often anymore. In some smaller resolutions it is still there. There is a dataTables_scrollBody and overflow hidden in the html causing this. A way to go is also to distribute the column width more efficiently. But please ensure the content appears as part of the page and is not a frame.

![screenshot from 2017-02-02 22-20-30](https://cloud.githubusercontent.com/assets/1583873/22568975/190a7130-e996-11e6-9a98-fdf115fcd70a.png)

**Comment by SaptakS** [comment]
@mariobehling, the scroll was kept in smaller resolutions to allow scrolling in table in smaller screen to see the entire content. Since the exact width can't be and shouldn't be put, I think for smaller resolution we should let the scroll be there. Maybe we can reduce a few pixels in media queries... But that will break many other designs...

**Comment by mariobehling** [comment]
@SaptakS I do not know any modern website that results in scroll bars within the page.

I also see that some columns contain a lot of content in a relatively thin area and other columns have empty spaces. We need a better distribution of the column width.

**Comment by SaptakS** [comment]
> I also see that some columns contain a lot of content in a relatively thin area and other columns have empty spaces. We need a better distribution of the column width.

I agree to this but that won't solve the problem of showing tables in smaller resolution.

> I do not know any modern website that results in scroll bars within the page.

I agree with this. But then we have made tables as our base of showing information from beginning. To replace it, we need to replace it everywhere now and think of some other alternative... Else we need to show them in the form of accordions in smaller screens where you will have only the list of events and click on the event to see the details instead of in table form...

@niranjan94 @magdalenesuo your views???

**Comment by SaptakS** [comment]
Also @mariobehling I think we can close this issue and continue this in #3138 because this is a problem in all tables...

**Comment by mariobehling** [comment]
Ok, follow up in #3138.

**Comment by mariobehling** [comment]
The abstract text showing up in the draft tab is still longer.

![screenshot from 2017-02-07 10-35-14](https://cloud.githubusercontent.com/assets/1583873/22685605/3bace1d0-ed21-11e6-8d31-d8697d9ed012.png)

**Comment by Himanshi-Khandelwal** [comment]
@mariobehling  It is working fine in my case.
![screenshot from 2017-02-09 00 56 37](https://cloud.githubusercontent.com/assets/17119462/22753628/ce79e624-ee62-11e6-939e-b614892b1ede.png)

**Comment by SaptakS** [comment]
@mariobehling works fine for me

![screenshot from 2017-02-09 01-02-21](https://cloud.githubusercontent.com/assets/9530293/22753878/a6804a68-ee63-11e6-86e8-44dbdd4b2b1a.png)
