### ISSUE TITLE
Unable to update email preferences 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-orga-server#3062]
since this morning I was unable to update email preferences. I tried to switch ON email updates but it always turned back to OFF mode. 

Secondly, the event I am co-organizer in does not show up in preferences.

Expected behavior: User should be able to control email notifications.

![updateemailpreferences](https://cloud.githubusercontent.com/assets/1658742/22403799/b9a28cf8-e622-11e6-8c77-9c6de7abe0b5.png)

**Comment by SaptakS** [comment]
@hpdang seems to be working for me. Can you please check and confirm.

![screenshot from 2017-02-03 00-57-02](https://cloud.githubusercontent.com/assets/9530293/22564797/ca348f62-e9ab-11e6-95d7-95d9487b721f.png)

**Comment by hpdang** [comment]
@SaptakS Issue is still there for me.

Also on the email settings page an event exists, that was deleted from the system long ago. Please see screenshot below.

![screenshot from 2017-02-02 22-56-38](https://cloud.githubusercontent.com/assets/1658742/22570401/698b1592-e99b-11e6-9e00-99d9ac473001.png)

**Comment by SaptakS** [comment]
@hpdang I think the issue is because all events are being fetched instead of the ones that are not in trash. That needs to be fixed. And as of not showing notifications for other events, I am thinking maybe it's implemented only for organisers and speakers. Maybe not co-organisers. Can that be a possibility?? @niranjan94 ?

**Comment by niranjan94** [comment]
Linked to related API parent issue.
