### ISSUE TITLE
Can we use a client side framework 

### ISSUE THREAD

**Issue by Rohanhacker** [fossasia/open-event-orga-server#3202]
We already have an api adding client side framework and separating client and server will allow more front end developers to contribute and make frontend more organised.

**Comment by niranjan94** [comment]
@Rohanhacker that is under consideration. But it would involve a continuous and intense development sprint along with a lot of contributors since it would be a major upgrade. API has to be modified too to add a lot of functionality. (Right now we support only basic CRUD operations)

As of now, our priorities are to fix bugs and move to production.

Closing this for later.
