### ISSUE TITLE
Increase standard font size of text

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3220]
The standard font size of the text and a number of areas is very small and often difficult to read, especially on the public event page, e.g. event information and call for speakers.

Please increase the font size. At the same time ensure the design is still working across the app. Also test your changes in depth in all areas that are affected from the css change.

![screenshot from 2017-02-19 06-53-20](https://cloud.githubusercontent.com/assets/1583873/23097504/886d0a10-f670-11e6-8957-0101f343a3dc.png)

**Comment by poush** [comment]
Working on this.

**Comment by poush** [comment]
What if we use "rem" units instead of "px".

Here are few snapshots with "1.35rem"

<img width="1440" alt="screen shot 2017-02-19 at 1 59 59 pm" src="https://cloud.githubusercontent.com/assets/1812082/23100619/fd0266fa-f6ab-11e6-9f98-f3cf59d8a1d9.png">
<img width="622" alt="screen shot 2017-02-19 at 2 00 10 pm" src="https://cloud.githubusercontent.com/assets/1812082/23100620/fd4da6f6-f6ab-11e6-9a48-c104631214f0.png">
<img width="1440" alt="screen shot 2017-02-19 at 2 00 57 pm" src="https://cloud.githubusercontent.com/assets/1812082/23100621/fd505fe0-f6ab-11e6-8d4c-56dd6b7ddbff.png">


with 1.45rem

<img width="1440" alt="screen shot 2017-02-19 at 2 03 40 pm" src="https://cloud.githubusercontent.com/assets/1812082/23100629/45ccec5c-f6ac-11e6-9862-1541107442fc.png">

**Comment by mariobehling** [comment]
Thanks. How can we avoid internal scrollbars in mobile views?

**Comment by poush** [comment]
We have to redesign the tickets UI for mobile in that case. We can use accordions like "collapsable" of bootstrap for this.

There are many places in orga server which require design changes to work on mobile. Many places where I removed one or more scrollbars fixes the issue for average/small screen sizes but not for mobiles. Administrator panel is not a big issue since most of the time admin and organizers would be using desktops/laptops for managing their event since a big list of data can't be optimized for a mobile view but the guest view should be mobile user-friendly.

**Comment by niranjan94** [comment]
`frontend` tag added. Will be continued in frontend repo

**Comment by niranjan94** [comment]
`frontend` tag added. Will be continued in frontend repo
