### ISSUE TITLE
Show a section for featured speakers on public event page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3232]
We already collect information on which speakers are featured.

Please implement a section featured speakers on the public event page and show them with their short bio (200 characters) next to them.

Show a heading "Featured Speakers"

![screenshot from 2017-02-23 02-33-16](https://cloud.githubusercontent.com/assets/1583873/23226430/79ce867a-f970-11e6-885b-0f8576e6c74b.png)

**Comment by poush** [comment]
Would like to work on this.

**Comment by mariobehling** [comment]
Thanks! Please keep the sizes of speaker images same as other speakers.

**Comment by poush** [comment]
My suggestion would be to maintain this size for all speakers,

<img width="1440" alt="screen shot 2017-02-23 at 4 53 48 pm" src="https://cloud.githubusercontent.com/assets/1812082/23257197/c99137e8-f9e8-11e6-9653-e61ad9c747d6.png">

And if we try to reduce size through grid we will get something like this 
<img width="1440" alt="screen shot 2017-02-23 at 4 54 32 pm" src="https://cloud.githubusercontent.com/assets/1812082/23257217/e56d044c-f9e8-11e6-89c4-e0c82768d5c7.png">

Plus the text there is reduced to 200 characters.

**Comment by poush** [comment]
@mariobehling Any suggestions? Also, do we need to show short_bio in mobile view as well?

**Comment by mariobehling** [comment]
The featured speakers section shows html "<p><span style="">". 

@poush Could you check, please?

**Comment by mariobehling** [comment]
The changes also resulted in the break of the speakers section.

![screenshot from 2017-02-25 21-32-15](https://cloud.githubusercontent.com/assets/1583873/23331486/eb5c6fe0-fba1-11e6-8ebc-2830b5ef3bb7.png)

**Comment by mariobehling** [comment]
* [ ] Display of social media icons also broken

**Comment by mariobehling** [comment]
* [ ] Display of social media icons not changed back to original display
* [ ] Speakers columns was changed from 5 columns to 4 columns for no reason

**Comment by mariobehling** [comment]
Indention of images and text should be same across sections. Please help to keep the style consistent.

* [ ] Change indention of featured speaker section to match the speaker section.

![screenshot from 2017-02-25 23-31-01](https://cloud.githubusercontent.com/assets/1583873/23332320/b687ea7c-fbb2-11e6-8708-e27a5e42e09b.png)

**Comment by poush** [comment]
@mariobehling Speaker images grid changed from 5 to 4 to ensure the same size of all speakers ( including featured ) 

```" Display of social media icons also broken" ```
Are you saying about centering them as they were before?

And sure I will fix this indentation issue.

**Comment by mariobehling** [comment]
> Speaker images grid changed from 5 to 4 to ensure the same size of all speakers

I did not see this was discussed here.

Please change it back to the grid of 5 speakers. Reason a) Images are not always in sufficient quality, b) the list of speakers gets too long. 5 speakers worked just fine for now.

> " Display of social media icons also broken"

Here you changed the padding around the icons or something. They are too close to the text now.
Correct you also changed the alignment without discussion or any hint beforehand.

It is great that you are contributing. Thank you. However, please make it easier for everyone to follow the flow of the project and implement only what is outlined in  issues. This helps to avoid long discussions and questions afterwards like now. If you want to change other things, please mention/discuss it beforehand.

**Comment by mariobehling** [comment]
Well, maybe you simply changed the paragraph style and now the icons are too small. It would be so good, if you could just change back everything that was not part of this issue.

**Comment by poush** [comment]
> I did not see this was discussed here.

Actually to make sure images are of same size as of featured speaker as you suggested me before, I made sure they are on same grid size. As per your suggestion I reverting the changes.
Yes, the margin was changed a little bit to make sure they fit with the featured section images. Making a fix for other speakers. 

Here is the progress/changes coming up in next PR

- [x] Display of social media icons not changed back to original display
- [x] Speakers section back to exactly what it was before

<img width="1440" alt="screen shot 2017-02-26 at 2 07 53 pm" src="https://cloud.githubusercontent.com/assets/1812082/23338301/fdbc1da8-fc2c-11e6-8e18-ae40f9cfeab5.png">
This speaker section is exactly same as it was before any of my PR.
Regarding grid, I didn't even changed it from 5 to 4 it was as 4 from the beginning. What I did was instead of keeping them of fixed size, I made them of full width so the images don't have to be centre aligned and therefore can be aligned with speaker images and get same size.
I suggested about this size in the first reply of this issue. Although I agree with you, it really makes the list look long.

> Well, maybe you simply changed the paragraph style and now the icons are too small. It would be so good, if you could just change back everything that was not part of this issue.

Not sure of which styling you are saying about. The icon sizes are same as they were before. I worked on icon sizes of featured speaker because the original size of nearby 14px are not making visible below the image so made them to 16px.

Apologies for the mistakes I did. I will try to make sure to undo the things you mentioned above.

**Comment by poush** [comment]
@niranjan94 @SaptakS @mariobehling 

> The featured speakers section shows html <p><span style="">

If I show substring of 200 characters by not escaping html in jinja, there is possibility that the html tags could be left open. May be we can either remove all html tags from the string before or disable wysiwyg editing on adding bio. Any suggestions ?

**Comment by poush** [comment]
@mariobehling can we add restriction of 200 characters at the biography input box for speaker?

**Comment by mariobehling** [comment]
@poush The solution should be same as on the Open Event Web app. Please try out the web app using the sample from 2016 - https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16.zip

**Comment by mariobehling** [comment]
@SaptakS The original columns of speaker was 5 columns. I think this does not have priority anymore. We can keep it as is now.

**Comment by SaptakS** [comment]
@mariobehling then I guess the issue is resolved.
