### ISSUE TITLE
Maintaining Consistency in the API

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-orga-server#3237]
The `key` which was `long_abstract` in the previous version of API now changed to `short_abstract`.
Also, the key `long_biography` from previous FOSSASIA 16 API sample has changed to  `short_biography` 
@SaptakS @niranjan94 we have to maintain a consistency between the server and the app. 

Please check the issue https://github.com/fossasia/open-event-webapp/issues/1061

**Comment by niranjan94** [comment]
Yep. I guess it's our fault for not informing the app teams about the key change. 
This was done quite sometime ago. `Jun 15, 2016` (https://github.com/fossasia/open-event-orga-server/commit/bd6e5947f8286ac824e44343f67ad842f7648024) to be exact. 

So at the point, API was still in a volatile stage with a lot of changes. But as of now, the API is pretty stable. It will not be undergoing any field name refactors in the near future and we'll also try not do them. If at all, we're doing, we'll ensure it is properly explained and the webapp and mobile app teams are notified so that they can do the appropriate change.

**Comment by niranjan94** [comment]
And also, I recommend the app teams have a look at API docs at https://open-event-dev.herokuapp.com/api/v1/ (which is always updated with the correct API specs) from time to time in case we miss something.

**Comment by Princu7** [comment]
@niranjan94, No problem, we will implement it accordance to the new changes :)

**Comment by niranjan94** [comment]
@Princu7 thanks :smile: ... closing this issue now

**Comment by mariobehling** [comment]
@aayusharora @Princu7 Please also take into account that there could be short and long bio. So, best would be "if short bio is not present, but long bio is present, then use long bio" (same for speakers info).
