### ISSUE TITLE
Do not add "Unscheduled Sessions" to the API and JSON or public schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3260]
If sessions are unscheduled, they should not be displayed publicly. Currently they are. Unscheduled sessions show up in the public schedule, are transferred through the API and saved in JSON files.

Expected: Please do not add unscheduled sessions to public data set. There should be a data field "null" or something in the time fields, that ensures they are not displayed. We still want the data of the sessions in e.g. the JSON (so we can save the whole event), but we do not want the display in a publicly generated site (e.g. the web app site).

**Comment by shubham-padia** [comment]
If the `microlocation` field of the session is null, the session is unscheduled. Rather than adding an extra redundant field in the api, we can add a note about this in `docs/general/api.md`. The client side application  e.g open-event-webapp can implement their own logic to see if the session is scheduled or not.
