### ISSUE TITLE
Images converted to large png images

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3300]
Most images uploaded to the event system are relatively small jpg files. The system seems to convert all images to large pngs that are shown in some parts of the app and provided as a source for the API as well. 

This is increasing the size of all images. With an larger number of events this potentially slows down the system. 

On the client side some of the pngs are 4 to 5 times bigger than the originally uploaded file. I worked on a mobile connection and used a lot of the bandwidth.

**Comment by SaptakS** [comment]
@mariobehling converting images from jpg to png automatically increases size and it is advised to do image operations on png rather than jpg because it then reduces the quality of image. So the original image upoaded maybe big. 

But we need to use only the resized-images rather than the original images. The resized images are smaller in size and match the dimensions as well. So it is advisable to use the exact resized image that is necessary rather than the original image. 

I will check wherever original image is used and replace them with resized images. That should solve the problem.
