### ISSUE TITLE
PNG Export from Full Screen Schedule not showing whole schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3367]
The png of the schedule from the full screen expanded view only shows part of the schedule. See below.

![timeline 10](https://cloud.githubusercontent.com/assets/1583873/23828610/6c1af892-0712-11e7-8461-3bec917fc9a6.png)

**Comment by CosmicCoder96** [comment]
@mariobehling working on this.

**Comment by LuD1161** [comment]
@mariobehling 
Working on this

**Comment by niranjan94** [comment]
@LuD1161 what's the progress on this front ?

**Comment by LuD1161** [comment]
@niranjan94 
Actually left it quite a while back , right now looking again into it.

**Comment by LuD1161** [comment]
@mariobehling @niranjan94 
I am unable to reproduce this issue due to **Schedule Not Found** , have raised an issue [Issue#3623](https://github.com/fossasia/open-event-orga-server/issues/3623).

![The error](https://cloud.githubusercontent.com/assets/17861054/26274292/943e89c8-3d64-11e7-88eb-49b094e91ebf.png)
