### ISSUE TITLE
Load times of tabs and pages very long

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3437]
Having events with loads of data increases the load times (sometimes to over 1 minute) a lot, e.g. events with many sessions, many tickets, speakers etc.

Please ensure tabs and pages load fast and implement a better page handling.

**Comment by SaptakS** [comment]
@mariobehling since we are de-coupling the orga server anyways and are moving to a more API oriented back-end, how much of a priority or bug is this issue?

**Comment by niranjan94** [comment]
Have to agree with @SaptakS on this. Implementing this in the current UI would require some extensive changes in the current UI and backend. Which IMO, is kinda pointless and a waste of time when we're moving to a new frontend that is gonna be much faster (since it will be calling the API in a paginated manner and loading only what is necessary)
