### ISSUE TITLE
Change logic for soft deletes

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3494]
In the current implementation, for soft-deletes we have two fields `in_trash` and `trash_date` (Example: see `app/models/event.py`) 

Instead, have one nullable datetime field called `deleted_at`. That field should have `null` as the default. If that field is null, then the record is not deleted. If it isn't null, then it is deleted. 

_(This is similar to the soft-delete implementation done in [Laravel Framework](https://laravel.com/docs/5.4/eloquent#soft-deleting))_

**Comment by aviaryan** [comment]
@niranjan94 I would like to work on this.

**Comment by rafalkowalski** [comment]
Here it's an example how we can solve it in sqlalchemy https://blog.miguelgrinberg.com/post/implementing-the-soft-delete-pattern-with-flask-and-sqlalchemy

**Comment by aviaryan** [comment]
@rafalkowalski That link shows a very similar implementation to our current situation, using a `deleted` bool variable instead of ours `in_trash`. And it doesn't store deleted time. 
What is suggested here is the best way IMO, we will now only use one variable and it will have the required data (deleted time) also.
