### ISSUE TITLE
Make file exports take into consideration the storage setting on the app

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3523]
Right now, file exports write the exported zip to the local file system by default irrespective of what the user's storage setting (google cloud, s3, local) is. Ensure the exported zip is placed in the appropriate location.

This is especially important when we have something like a kubernetes deployment where the local-storage is volatile and isolated by default. Local storage is not sharable b/w pods by default. (In our case, celery's local storage is isolated from the web app's local storage, so, creating a shared persistent storage space that is read-writable by multiple pods is both tricky and slightly unreliable during re-deployments)

**Comment by aviaryan** [comment]
Adding to this issue:
Right now we are not deleting the exported zip. As the zip is being stored in a volatile storage, this wasn't seen necessary. But now as the zip will be stored on S3 or google cloud, they will have to be deleted at some point (+ 24 hours) so that they don't end up taking space. A celery scheduled job will easily do this. 

PS - I would have loved to fix this issue but alas, end semester exams this week.

**Comment by poush** [comment]
I'm working on this
