### ISSUE TITLE
Test Google Cloud deployment with Kubernetes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3543]
The setup with Kubernetes has issues at points and there are ideas to improve the setup. We need everyone to understand it and set up a system for her/himself with Kubernetes. Please report your experience and share a link here. 

@shreyasnbhat @rohanagarwal94 @Shailesh351 @arpitdec5 @mahikaw @geekyd @harshitagupta30 @anu-007 @sumedh123 @CosmicCoder96 @utkarshnath @Ronak-59 @mejariamol @iamareebjamal @LuD1161 @magdalenesuo @poush @enigmaeth @shubham-padia @Princu7 @SaptakS

**Comment by shubham-padia** [comment]
The link for the test app is http://104.198.101.205:8080/ (working as of may 16 17:50 IST)

**Comment by niranjan94** [comment]
@shreyasnbhat @rohanagarwal94 @Shailesh351 @arpitdec5 @mahikaw @geekyd @harshitagupta30 @anu-007 @sumedh123 @CosmicCoder96 @utkarshnath @Ronak-59 @mejariamol @iamareebjamal @LuD1161 @magdalenesuo @poush @enigmaeth @shubham-padia @Princu7 @SaptakS

The kubernetes configuration has been refactored and updated (the updated config and guide can be found in the `nextgen` branch).
- Config -> https://github.com/fossasia/open-event-orga-server/tree/nextgen/kubernetes
- Guide -> https://github.com/fossasia/open-event-orga-server/blob/nextgen/docs/installation/gce-kubernetes.md 

It would be better if all of you test that out instead of the current configuration. The new config should also fix any issues you had with NFS Server.

**Comment by CosmicCoder96** [comment]
The link for my  test app (as updated on the wiki) is htt[s://orga.gq 
Feedback:
The only very minor glitch I faced while following the guide was: 
It was required to use `gcloud auth login` to authorise. Else it resulted in an 
`insufficient permission` error.
Platform : Mac OS Sierra

**Comment by rohanagarwal94** [comment]
https://orga.ml/

**Comment by niranjan94** [comment]
@rohanagarwal94 please add it to https://github.com/fossasia/open-event-orga-server/wiki
