### ISSUE TITLE
Implement Order api with proper permissions and relationships

### ISSUE THREAD

**Issue by magdalenesuo** [fossasia/open-event-orga-server#3700]

**Comment by niranjan94** [comment]
@poush please propose your implementation for the order flow here.

**Comment by poush** [comment]
I think the first is to keep the status numbers instead of text. We should have small Integer field for keeping the status of any order. Keeping the same database structure, 
as per #3468


1. *CREATE*  ```\orders```: Creating an order with pending status and return the payment link
payment link should have endpoint of ```\payments\<int:id>```. Permission of this access point would be global so that anyone can create orders.

2. *GET* ```\orders\<int:id>```: Get order detail. Will contain the payment link if the status is pending. 

3. *GET, UPDATE*, ```\order_status\<int:order_id>\<int:status_code>``` to get and update status. Where Update is restricted to event staff only. 

4. *UPDATE,DELETE*, ```/Orders/<int:id>```: Update the order details and to delete the Order.

__Payment__:

 ```/payments/<int:id>```: Redirect to payment gateway and complete the payment if not already completed. On return the callback url ```/payments/<int:id>/confirm?``` will be used to confirm the Payment status and Order status in API Server.

Flow: 

Order Created -> Get Payment Link -> Go to Payment Link -> Redirected to payment gate -> Call bak url to confirm the order and payment -> Original Page refreshed -> Continue with the order ( get tickets )

**Comment by niranjan94** [comment]
@poush did you look at the current implementation first ? I don't think you did ... Paypal and stripe have different payment flows.

**Creating an order:**

`POST /v1/orders` - Create an order. Event admins should be able to change the status attribute here. The status attribute should be optional. But if an event admin provides the status attribute with a particular status, then that's final. If event admin says status is paid, then it's paid. No payment link. 

The response would have the usual order object with one additional attribute maybe called `payment-url`. Which can have either of the two things. 
1. In case of stripe, it'll just have a value `strip`. (Stripe needs no payment URL. The payment process will be handled by Stripe's javascript client. No extra information required at this point.)
2. In case of PayPal, this field should contain the value returned by PayPalPaymentsManager.get_checkout_url (Can be found inside `app/helpers/payment.py`). While generating the checkout URL, you will require to give a `RETURNURL` and a `CANCELURL`. Both should point to a page on the FE since both are user-facing pages. To generate that, add a new field to the settings model, `frontend-url` that would have something like `https://nextgen.eventyay.com`. To that settings value, append `/orders/<order_identifier>/payment/success` or `/orders/<order_identifier>/payment/cancelled` for `RETURNURL` or `CANCELURL` respectively. The FE will handle it from there.

**Making a payment:**
 
 The FE or which ever client, would take things up from here. No BE involvement needed. 

**Confirming and charging a payment:**

 `POST /v1/orders/<order_identifier>/charge`

 ***Paypal:***
 In the case of paypal, this will have no payload. But you need to charge the payment using `TicketingManager.charge_paypal_order_payment` in `app/helpers/ticketing.py` and return the final order object. 

 ***Stripe:***
 In this case, there will be one payload. 

 ```
 {
 	"token": "a-token-code-returned-by-stripe"
 }
```

With the token, charge the payment using an implementation similar to `TicketingManager.charge_stripe_order_payment in `app/helpers/ticketing.py` and return the final order object.

In both cases, update order status accordingly whether the payment charging fails or succeeds. 

---

Apart from this the usual READ, UPDATE and DELETE would be there.

**Comment by poush** [comment]
Work in progress. Need to ensure some points like, applying discount codes, amount calculations, applying discounts to the amount ( implemented need to test more ). Plus there is something with my paypal sandbox not sure why always giving me the failed response.
