### ISSUE TITLE
Enhance and correct Tracks API

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3815]
- Remove `track_image_url` (Both API and DB. There is no data anyway)
- Remove `location` (Both API and DB. There is no data anyway)
- Add `font_color` to API response (only API response. No DB field. Dynamic based on color. See #3568 for old implementation.)
- Update the above details in the API Blueprint too

**Comment by magdalenesuo** [comment]
@niranjan94 One question, would it better if:
1) we allow client to post/patch the font-color and we deleted it (not update it) in the api and show a message saying 'it will not be updated since it is automated' or something like that.
or
2) raise an error message if they try to post/patch font-color.

**Comment by niranjan94** [comment]
Allow the client to post/patch font color for now. But ignore any changes to it.
