### ISSUE TITLE
Create marketer relationship with access_code and discount_code api

### ISSUE THREAD

**Issue by magdalenesuo** [fossasia/open-event-orga-server#4093]
Endpoints:
- `/access-codes/<access_code_id/marketer` (detail)
-  `/discount-codes/<access_code_id/marketer` (detail)
- `/access-codes/<access_code_id/relationships/marketer` (relationship)
- `/discount-codes/<access_code_id/relationships/marketer` (relationship)
- ~~`/marketer/<user_id/access-codes` (list)~~
- ~~`/marketer/<user_id/discount-codes` (list)~~
- ~~`/marketer/<user_id/relationships/discount-codes` (relationship)~~
- ~~`/marketer/<user_id/relationships/access-codes` (relationship)~~

**Comment by niranjan94** [comment]
@magdalenesuo 

- `/marketer/<user_id/access-codes` (list)
- `/marketer/<user_id/discount-codes` (list)
- `/marketer/<user_id/relationships/discount-codes` (relationship)
- `/marketer/<user_id/relationships/access-codes` (relationship)

Wont exist. These will be part of the user endpoints since marketer is of type user. We're only calling the relationship as marketer. The resource is still user.

**Comment by magdalenesuo** [comment]
@niranjan94 okay. I'll remove those endpoints. 
Yes. I just named the endpoint that way for better understanding. 😅  It will still be a user endpoint and resource user.
