### ISSUE TITLE
Create APIs for SponsorType

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#674]
To elaborate more on this, the sponsor types needed apis so the event creator can specify them (like "Platinum Sponsor", "Gold Sponsor") and associate sponsors to them.

**Comment by mariobehling** [comment]
I missed this. This seems completely unnecessary and against our goals to keep it simple. All sponsorship information should go into the sponsors API, except if there is a very good reason. What is the very good reason? We would end up with dozens of APIs if such a messy way is going to be continued. The APIs were clearly outlined with @rafalkowalski. The sponsorship API issue is here https://github.com/fossasia/open-event-orga-server/issues/615 What is going on?

**Comment by aviaryan** [comment]
@mariobehling SponsorType was created because it allows organizers to create their **own sponsor types**. Then when they are adding a sponsor, they can select the type from the list (of sponsor types). They won't have to type it. 
Should we move SponsorType inside Sponsors ?
In that case the API will be `events/<id>/sponsors` for sponsors and `events/<id>/sponsors/types` for sponsor types . (Sponsor types will not be a parent API now). 
The GET API return for sponsors will look like. 

```json
{
        "description": 'abcd', 
        "id": 1, 
        "logo": 'http://link.com/img.png', 
        "name": "TestSponsor1_1", 
        "sponsor_type": {
            "id": 1, 
            "label": "Gold"
        },
        "url": 'http://web.com'
    }, 
```
or we can just show the label in sponsor_type and not the whole object ??

```json
{
    "sponsor_type": "Gold"
}
```

Also there is Format and Level in sessions . As you have not mentioned them in #799, should we move them inside sessions ?

**Comment by mariobehling** [comment]
What is level for? I thought it is for sponsorship level. I am not sure, if we need level in sessions at the moment.

**Comment by aviaryan** [comment]
@mariobehling 

> What is level for? 

It was there from the start. I think it is like difficult level of session. (not sure)

> I am not sure, if we need level in sessions at the moment.

Should I remove level then ? If you are not sure, we can just hide it from the API for the moment.

Also what about sponsor_types and formats ? Should I move them inside their parents or let them be the way they are ?

**Comment by mariobehling** [comment]
@aviaryan Please refer here https://github.com/fossasia/open-event-orga-server/issues/799

There is a list of APIs. If we need other APIs state why.

Please make list of the fields for each API and discuss details in the specific issue. Some questions are not blockers, e.g. the question of levels. You can still continue and if necessary open a separate issue to follow up later. At the moment we are lacking the global implementation, even though we already have JSON examples. Please focus on the bigger questions and we will go into details as we proceed.
